services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\UserActivityReportBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\UserActivityReportBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

